### ISSUE TITLE
Error: Cannot find module 'tern/plugin/node-express.js'

### ISSUE THREAD

**Issue by brunolemos** [angelozerr/tern-lint#69]
It's not finding external plugins. If I remove them from .tern-project file, it works fine.
Tried installed everything locally and globally.

`brunolemos@brunolemos-mac easycarros-api (stage) $ tern-lint src/ --format
module.js:341
    throw err;
    ^

Error: Cannot find module 'tern/plugin/node-express.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:27:19)
    at loadPlugins (/usr/local/lib/node_modules/tern-lint/bin/lint:94:27)
    at startServer (/usr/local/lib/node_modules/tern-lint/bin/lint:130:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/tern-lint/bin/lint:126:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)`

**Comment by angelozerr** [comment]
Could you share your project please?

**Comment by brunolemos** [comment]
Closing because I haven't faced this error since I reported.
