### ISSUE TITLE
type undefined

### ISSUE THREAD

**Issue by davidosomething** [angelozerr/tern-lint#71]
running tern-lint on a project I got the following:

```
TypeError: Cannot read property 'isEmpty' of undefined
    at validateCallExpression (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/lint.js:212:15)
    at c (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/acorn/dist/walk.js:39:16)
    at Object.skipThrough (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/acorn/dist/walk.js:169:3)
    at c (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/acorn/dist/walk.js:38:15)
    at Object.base.ExpressionStatement.base.ParenthesizedExpression (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/acorn/dist/walk.js:186:10)
    at c (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/acorn/dist/walk.js:38:15)
    at Object.exports.searchVisitor.walk.make.Statement (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/tern/lib/infer.js:1929:7)
    at c (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/acorn/dist/walk.js:38:15)
    at Object.base.Program.base.BlockStatement (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/acorn/dist/walk.js:180:5)
    at c (/Users/david/.config/nvm/versions/node/v4.3.2/lib/node_modules/tern-lint/node_modules/acorn/dist/walk.js:38:15)
```

**Comment by sheerun** [comment]
same

**Comment by angelozerr** [comment]
Please share the simple js file content whch causes this problem. Thanks!

**Comment by sheerun** [comment]
@angelozerr 

```
class Foo extends Bar {
  constructor() {
    super();
  }
}
```
